# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - phantomx_arm_controller
    - phantomx_gripper_controller

  phantomx_arm_controller:
    type: FollowJointTrajectory
    joints:
      - arm_shoulder_pan_joint
      - arm_shoulder_lift_joint
      - arm_elbow_flex_joint
      - arm_wrist_flex_joint
      - gripper_fake_link_joint
      - gripper_link_joint
    action_ns: follow_joint_trajectory
    default: true
  phantomx_gripper_controller:
    type: GripperCommand
    joints:
      - gripper_joint
    action_ns: gripper_cmd
    default: true
    