# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 20  # Hz

    phantomx_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    phantomx_gripper_controller:
      type: position_controllers/GripperActionController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

phantomx_arm_controller:
  ros__parameters:
    joints:
      - arm_shoulder_pan_joint
      - arm_shoulder_lift_joint
      - arm_elbow_flex_joint
      - arm_wrist_flex_joint
      - gripper_fake_link_joint
      - gripper_link_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true
phantomx_gripper_controller:
  ros__parameters:
    joint: gripper_joint